### ISSUE TITLE
Icon not pulling through if used as a Build Content: Create Item

### ISSUE THREAD

**Issue by ruthsmalley** [celtic-project/bb-basiclti#1] opened 2018-05-03 09:48 UTC
Hi,

I am using the B2 to integrate Talis into our Blackboard set up.  Talis provide a url link to their icons.

In our staging environment I am using version 3.2.4 of the Basic LTi tools on Blackboard Q2 2017 CU5 and the icons pull through as expected whether I set Talis up as a Create Item or as a Course Tool.

On my test environment I am running version 3.3 of the Basic LTi tool and Blackboard Q2 2018 pre-release evaluation version.  

The icons are pulling through if I add Talis as a course tool, but not if I add them as Build Content: Create Item.  I am getting an icon but it is one I don't recognise, two arrows in a circle, one blue and one orange.

Any help appreciated.

Ruth

**Comment by spvickers** [comment] 2018-05-03 10:54
Thanks for the message; I will try to replicate this issue.  Do you know whether Talis is using the ContentItemMessage (Deep Linking) when creating items on course pages?

**Comment by ruthsmalley** [comment] 2018-05-03 10:58
Hi Stephen,

Thanks for your help.  I'm afraid I don't.  I'm pretty new to LTi so quite prepared for this to be something I've done.  I've followed the instructions on the Talis help page 

https://support.talis.com/hc/en-us/articles/206319649-Blackboard-and-Talis-Aspire-Reading-Lists-LTI-Tool-setup 

which I think is publicly available.  

Ruth

**Comment by spvickers** [comment] 2018-05-03 11:10
I think I may have replicated your issue, but only when you have not added the tool to one of the menus.  If you have not done this, then please try this as a workaround until the next release.  On the settings page for the bulding block I assume you have "None" in the Menu column for the Talis tool.  Select the tool and then select a menu from the "Content menu" dropdown list.

**Comment by ruthsmalley** [comment] 2018-05-03 11:14
I think I already had it set up as a menu tool.  These are my settings:

![image](https://user-images.githubusercontent.com/38722875/39573546-8acda2ba-4ecb-11e8-837d-68c74c61b5ac.png)

**Comment by spvickers** [comment] 2018-05-03 11:22
Well, this is working for me, so I cannot explain it.  Can you send me (stephen at spvsoftwareproducts.com) the XML definition of your tool (available from the quick menu for the tool on the settings page) so I can take a closer look at how your tool is setup?

**Comment by ruthsmalley** [comment] 2018-05-03 11:36
Thanks again for all your help.  It could be that it is the early Q2 2018 version of Blackboard that is the problem.  We will be upgrading to the production release on our test server soon, so I can test further then.  I've attached the xml (within a zip file as xml won't upload), but I copied and pasted this from the staging server set up (where things were working).  

[readin.zip](https://github.com/celtic-project/bb-basiclti/files/1970627/readin.zip)

**Comment by spvickers** [comment] 2018-05-03 11:49
Thanks, I did give you my email address to send it to.  Anyway, I don't think a copy from a server where it is working will help me identify the cause; I need to try to replicate the setup on the server where it is not working.

**Comment by spvickers** [comment] 2018-05-03 12:06
Don't worry, I think I have found the cause.  The icon is correctly displayed when the item is first created, but is lost when the item is updated.  I'll work on a fix for this.

**Comment by ruthsmalley** [comment] 2018-05-03 12:45
Thanks.  I'd missed that you gave me your email address.  The xml was downloaded today from the test server (where the problem is), but it is (should be) the same as the other server as that's where I copied it from.  Glad you've spotted the problem.  Thanks again for all your help.  It really is a great little tool.

**Comment by spvickers** [comment] 2018-05-15 15:24
Resolved in 3.3.1

**Closed as completed by spvickers** 2018-05-15 15:24 UTC
